title: "Sunmeet's Zero Point"
description: "Personal site of Sunmeet Singh"
baseurl: "" # the subpath of your site (leave empty if at root, i.e. sunmeetsingh.github.io)
url: "https://sunmeetsingh.github.io"

google_analytics: "G-CK9PF3RYND"

# Build settings
markdown: kramdown
theme: minima   # optional, only if you want to use the minima theme
plugins:
  - jekyll-feed # safe plugins GitHub Pages supports


